spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/glucon
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 4000

server:
  error:
    include-message: always